admissionController:
  serviceMonitor:
    enabled: true
backgroundController:
  serviceMonitor:
    enabled: true
cleanupController:
  serviceMonitor:
    enabled: true
reportsController:
  serviceMonitor:
    enabled: true

grafana:
  enabled: true
  grafanaDashboard:
    enabled: true